name: Build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'adopt'
    - name: Setup Keystore
      run: |
        echo "${{ secrets.SIGNING_KEY }}" > release.b64
        base64 -d release.b64 > release.keystore
    #- name: mobsfscan
    #  uses: MobSF/mobsfscan@0.2.0
    #  with:
    #    args: '. --sarif --output results.sarif || true'
    #- name: Upload mobsfscan report
    #  uses: github/codeql-action/upload-sarif@v2
    #  with:
    #    sarif_file: results.sarif
    - name: Build with Gradle
      run: |
        ./gradlew clean assembleRelease \
        -PKEYSTORE=../release.keystore \
        -PKEYSTORE_PASSWORD=${{ secrets.KEY_STORE_PASSWORD }} \
        -PKEY_ALIAS=${{ secrets.ALIAS }} \
        -PKEY_PASSWORD=${{ secrets.KEY_PASSWORD }} \
        -PRELEASE_MAPS_MAPCACHE_API_KEY=${{ secrets.RELEASE_MAPS_MAPCACHE_API_KEY }}
    - run: ./gradlew lint
    - uses: yutailang0119/action-android-lint@v3.1.0
      with:
        report-path: build/reports/*.xml
        follow-symbolic-links: true
    - name: print lint xml results
      uses: hidakatsuya/action-report-android-lint@v1.1.4
      with:
        result-path: 'mapcache/build/reports/lint-results-debug.xml'
        fail-on-warning: false
    - name: Verify Signature
      run: $ANDROID_SDK_ROOT/build-tools/33.0.1/apksigner verify --print-certs mapcache/build/outputs/apk/release/mapcache.apk
    - name: List files in the repository
      run: |
        ls -R ${{ github.workspace }}
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: mapcache
        path: mapcache/build/outputs/apk/release/mapcache.apk
